### ISSUE TITLE
Is it possible for the email field to be filled in by default during external provider auth

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#62] opened 2018-08-25 01:51 UTC
When a user authenticates with Microsoft, Google or Facebook, the user must still enter an email address for our site. Shouldn't this be available by the external provider?

**Comment by elainetao829** [comment] 2018-09-03 04:49
@d33pspace could you please delete my linked external accounts so that I can see the 1st time log in with external accounts now?

**Comment by elainetao829** [comment] 2018-09-03 04:59
I tried to log in with Microsoft today, and failed. The reason is the same email address of my Microsoft account has been registered before. But I was registered the email account internally, not as an external account.

I think the approriate solution for this scenario could be, the website asked me do I want to link my microsoft account with my internal account, i.e. user opens user management and goes to tab Password, there would be a (1) external account at least.

**Comment by elainetao829** [comment] 2018-09-03 04:59
The Chinese on the log in button is not right here. It should be "登录“

![image](https://user-images.githubusercontent.com/42002784/44968210-33d06880-af79-11e8-826e-b8245b775932.png)

**Comment by d33pspace** [comment] 2018-09-04 00:34
I deleted your gmail account. If you need me to remove Facebook or Microsoft please advise via Upwork the specific accounts that are linked.

**Comment by elainetao829** [comment] 2018-09-10 14:47
@d33pspace I think my google account is still there, or did I miss the verification message... Could you please delete that again?

2. A new issue #103 is found which is similar to this problem.

**Comment by d33pspace** [comment] 2018-09-10 23:32
@elainetao829 I removed your Google account on staging. But to be honest, I'm not sure what the implications of this are. If there is any unusual behavior it's possible that there is data not fully purged, either on our side or Google's. Just let me know if you're unable to test because of this. 

By the way, this issue is about the system asking for an email upon signing in with an external provider for the first time. Now the system should suggest the email associated with your external provider account. I'm not clear at this point if you're not able to test this because of errors, or if there are other issues being raised here.

**Comment by d33pspace** [comment] 2018-09-11 05:28
@elainetao829 I agree we should fix this. But strangely enough, I just deleted my own gmail address from the staging database and then attempted to log in to staging.renewal365.org and I didn't have a problem. I've removed your gmail from the database again. Can you try once more to confirm this?

**Comment by elainetao829** [comment] 2018-09-11 13:17
It cannot be reproduced on my side either. But on the same time, there is no confirmation page show up as well. I think we did not delete the account clean enough. Could you please investigate if it's possible to clean it up or it's some work that needs Google to do?

**Comment by d33pspace** [comment] 2018-09-11 23:12
As you remember, before, after signing in with an external provider, the user was directed to a page to enter their email. Now we have fixed it so the email account provided by the external provider is automatically used. So the confirmation is skipped and the user is immediately signed in.

I think during the donation process, this is best because the user is simply directed immediately to the credit card detail entry page. But what is confusing is, if a user signs in directly by navigating directly to the log in page without attempting to make a gift, the user is signed in and returned to the home page, and the only thing that indicates the user signed in successfully is their email account displays in the navigation bar. 

Am I understanding and experiencing this the same as you? If so, I understand the possible confusion of signing in directly from the log in page, however, I like how this solution is implemented for users who are making a payment. So as long as there are no errors right now, I suggest keeping this as-is and revisiting the issue at a later time. 

I've removed your gmail from the database so you can confirm again if you'd like.

**Comment by elainetao829** [comment] 2018-09-12 12:41
Hi @d33pspace I'm totally agree with you. I just logged in with google accounts again, the error page was not coming out. So I'm closing this ticket now.

**Closed by elainetao829** 2018-09-12 12:41 UTC
Labels: authentication, ready for testing
